
export const songListMaster = [
    { artist: "Guns N' Roses", title: 'Sweet Child O Mine  ' },
    { artist: "Plain White T's", title: 'Hey There Delilah  ' },
    { artist: "Plain White T's", title: 'Rhythm Of Love  ' },
    { artist: '3 Doors Down', title: 'Its Not My Time  ' },
    { artist: '3 Doors Down', title: 'Kryptonite' },
    { artist: 'A Great Big World', title: 'Say Something  ' },
    { artist: 'A Rocket to the Moon', title: 'Baby Blue Eyes' },
    { artist: 'Adele', title: 'Easy On Me' },
    { artist: 'Adele', title: 'Rolling In The Deep  ' },
    { artist: 'Adele', title: 'Set Fire To The Rain' },
    { artist: 'Adele', title: 'Skyfall  ' },
    { artist: 'Adele', title: 'Someone Like You  ' },
    { artist: 'Adele', title: 'When We Were Young' },
    { artist: 'AJR', title: 'Sober Up' },
    { artist: 'Alex Clare', title: 'Too Close' },
    { artist: 'Alex G ((Sandy A', title: 'Payphone Acoustic' },
    { artist: 'All Time Low', title: 'Backseat Serenade' },
    { artist: 'American Authors', title: 'Best Day Of My Life' },
    { artist: 'Amy Winehouse', title: 'Valerie' },
    { artist: 'Andrew McMahon', title: 'Cecilia And The Satellite' },
    { artist: 'Anna Nalick', title: 'Breathe 2 Am' },
    { artist: 'Atlas Genius', title: 'Trojans  ' },
    { artist: 'Backstreet Boys', title: 'I Want It That Way  ' },
    { artist: 'Bastille', title: 'Bad Blood' },
    { artist: 'Bastille', title: 'Blame' },
    { artist: 'Bastille', title: 'Flaws' },
    { artist: 'Bastille', title: 'Lethargy' },
    { artist: 'Bastille', title: 'Pompeii Acoustic  ' },
    { artist: 'Ben E. King', title: 'Stand By Me' },
    { artist: 'Bill Withers', title: 'Aint No Sunshine' },
    { artist: 'Billie Eilish', title: 'Happier Than Ever' },
    { artist: 'Billie Eilish', title: 'Lovely' },
    { artist: 'Billie Eilish', title: 'Ocean Eyes' },
    { artist: 'Birdy', title: 'Skinny Love  ' },
    { artist: 'Blink-182', title: 'All The Small Things' },
    { artist: 'Blink-182', title: 'I Miss You  ' },
    { artist: 'Blues Traveler', title: 'Hook' },
    { artist: 'Bon Jovi', title: 'Wanted Dead Or Alive' },
    { artist: 'Briston Maroney', title: 'Freakin Out On The Interstate' },
    { artist: 'Britney Spears', title: 'Toxic  ' },
    { artist: 'Bruno Mars', title: 'Grenade' },
    { artist: 'Bruno Mars', title: 'It Will Rain' },
    { artist: 'Bruno Mars', title: 'Locked Out Of Heaven' },
    { artist: 'Bruno Mars', title: 'The Lazy Song  ' },
    { artist: 'Bruno Mars', title: 'When I Was Your Man' },
    { artist: 'Cage the Elephant', title: 'Cigarette Daydreams' },
    { artist: 'Cage the Elephant', title: 'Cold Cold Cold' },
    { artist: 'Calum Scott', title: 'Dancing On My Own' },
    { artist: 'Camila Cabello', title: 'Havana' },
    { artist: 'Cee Lo Green', title: 'Forget You' },
    { artist: 'Chris Stapleton', title: 'Tennessee Whiskey' },
    { artist: 'Christina Perri', title: 'A Thousand Years' },
    { artist: 'Christina Perri', title: 'Jar Of Hearts' },
    { artist: 'Colbie Caillat', title: 'Bubbly' }
{ artist: 'Coldplay', title: 'A Sky Full Of Stars' },
    { artist: 'Coldplay', title: 'Clocks' },
    { artist: 'Coldplay', title: 'Fix You  ' },
    { artist: 'Coldplay', title: 'The Scientist  ' },
    { artist: 'Coldplay', title: 'Viva La Vida' },
    { artist: 'Coldplay', title: 'Yellow' },
    { artist: 'Counting Crows', title: 'Mr Jones' },
    { artist: 'Daithi De Nogla', title: 'Your Love' },
    { artist: 'Daniel Powter', title: 'Bad Day' },
    { artist: 'Daughtry', title: 'Crashed Acoustic' },
    { artist: 'Daughtry', title: 'Feels Like Tonight' },
    { artist: 'Daughtry', title: 'Ghost Of Me' },
    { artist: 'Daughtry', title: 'Home Acoustic' },
    { artist: 'Daughtry', title: 'Its Not Over' },
    { artist: 'Daughtry', title: 'Life After You' },
    { artist: 'Daughtry', title: 'No Surprise  ' },
    { artist: 'Daughtry', title: 'On The Inside' },
    { artist: 'Daughtry', title: 'What About Now' },
    { artist: 'David Guetta', title: 'Titanium  ' },
    { artist: 'Dean Lewis', title: 'Be Alright' },
    { artist: 'Death Cab for Cutie', title: 'I Will Follow You Into The Dark  ' },
    { artist: 'Dermot Kennedy', title: 'Giants' },
    { artist: 'Dermot Kennedy', title: 'Outnumbered' },
    { artist: 'Des Rocs', title: 'Maybe I' },
    { artist: 'Disturbed', title: 'The Sound Of Silence' },
    { artist: 'Eagles', title: 'Hotel California' },
    { artist: 'Ed Sheeran', title: 'Bad Habits' },
    { artist: 'Ed Sheeran', title: 'Beautiful People' },
    { artist: 'Ed Sheeran', title: 'Best Part Of Me' },
    { artist: 'Ed Sheeran', title: 'Bloodstream' },
    { artist: 'Ed Sheeran', title: 'Castle On The Hill' },
    { artist: 'Ed Sheeran', title: 'Dont' },
    { artist: 'Ed Sheeran', title: 'I See Fire  ' },
    { artist: 'Ed Sheeran', title: 'Im A Mess' },
    { artist: 'Ed Sheeran', title: 'Lego House' },
    { artist: 'Ed Sheeran', title: 'Make It Rain  ' },
    { artist: 'Ed Sheeran', title: 'Nina' },
    { artist: 'Ed Sheeran', title: 'Photograph' },
    { artist: 'Ed Sheeran', title: 'Shivers  ' },
    { artist: 'Ed Sheeran', title: 'The A Team  ' },
    { artist: 'Ed Sheeran', title: 'Thinking Out Loud  ' },
    { artist: 'Ed Sheeran', title: 'Visiting Hours Live' },
    { artist: 'Edward Sharpe and the Magnetic Zeros', title: 'Home' },
    { artist: 'Elton John', title: 'Rocket Man' },
    { artist: 'Elvis Presley', title: 'Cant Help Falling In Love' },
    { artist: 'Everlast', title: 'What Its Like' },
    { artist: 'Fall Out Boy', title: 'Alone Together Acoustic' },
    { artist: 'Five for Fighting', title: '100 Years' },
    { artist: 'Fleetwood Mac', title: 'Landslide' },
    { artist: 'Foo Fighters', title: 'Everlong' },
    { artist: 'Foo Fighters', title: 'My Hero Acoustic' },
    { artist: 'Foster the People', title: 'Pumped Up Kicks' },
    { artist: 'Frank Sinatra', title: 'Fly Me To The Moon  ' },
    { artist: 'Friday Pilots Club', title: 'Would You Mind' },
    { artist: 'Fun.', title: 'We Are Young' },
    { artist: 'Garth Brooks', title: 'Friends In Low Places' },
    { artist: 'Gary Allan', title: 'Every Storm Runs Out Of Rain' },
    { artist: 'Gary Jules', title: 'Mad World' },
    { artist: 'George Ezra', title: 'Barcelona' },
    { artist: 'George Ezra', title: 'Blame It On Me' },
    { artist: 'George Ezra', title: 'Budapest' },
    { artist: 'Gnarls Barkley', title: 'Crazy' },
    { artist: 'Goo Goo Dolls', title: 'Iris  ' },
    { artist: 'Goo Goo Dolls', title: 'Slide' },
    { artist: 'Gorillaz', title: 'Feel Good Inc' },
    { artist: 'Green Day', title: 'Boulevard Of Broken Dreams' },
    { artist: 'Green Day', title: 'Wake Me Up When September Ends' },
    { artist: 'Grover Washington Jr.', title: 'Just The Two Of Us' },
    { artist: 'Gym Class Heroes', title: 'Stereo Hearts  ' },
    { artist: 'Harry Styles', title: 'Sign Of The Times' },
    { artist: 'Harry Styles', title: 'Watermelon Sugar' },
    { artist: 'Hinder', title: 'Lips Of An Angel' },
    { artist: 'Hoobastank', title: 'The Reason' },
    { artist: 'Howie Day', title: 'Collide  ' },
    { artist: 'Hozier', title: 'Almost Sweet Music' },
    { artist: 'Hozier', title: 'Angel Of Small Death And The Codeine Scene' },
    { artist: 'Hozier', title: 'Cherry Wine' },
    { artist: 'Hozier', title: 'Like Real People Do' },
    { artist: 'Hozier', title: 'Take Me To Church  ' },
    { artist: 'Hozier', title: 'The Humours Of Whiskey' },
    { artist: 'Hozier', title: 'To Be Alone' },
    { artist: 'Hozier', title: 'Work Song' },
    { artist: 'Imagine Dragons', title: 'Bad Liar' },
    { artist: 'Imagine Dragons', title: 'Believer' },
    { artist: 'Imagine Dragons', title: 'I Bet My Life' },
    { artist: 'Imagine Dragons', title: 'Its Time' },
    { artist: 'Imagine Dragons', title: 'Warriors' },
    { artist: 'Imagine Dragons', title: 'West Coast' },
    { artist: 'Incubus', title: 'Drive Acoustic' },
    { artist: 'James Arthur', title: 'Say You Wont Let Go  ' },
    { artist: 'James Bay', title: 'Hold Back The River Acoustic' },
    { artist: 'James Bay', title: 'Let It Go  ' },
    { artist: 'Jason Mraz', title: 'Im Yours  11' },
    { artist: 'Jason Mraz', title: 'Lucky' },
    { artist: 'Jeff Buckley', title: 'Hallelujah  ' },
    { artist: 'John Legend', title: 'All Of Me' },
    { artist: 'John Mayer', title: 'Half Of My Heart' },
    { artist: 'John Mayer', title: 'Heartbreak Warfare  ' },
    { artist: 'Johnny Cash', title: 'Folsom Prison Blues  ' },
    { artist: 'Johnny Cash', title: 'Hurt  ' },
    { artist: 'Journey', title: 'Dont Stop Believin' },
    { artist: 'JP Saxe', title: 'If The World Was Ending' },
    { artist: 'Judah & The Lion', title: 'Suit And Jacket' },
    { artist: 'Justin Bieber', title: 'Love Yourself' },
    { artist: 'Kaleo', title: 'Way Down We Go Live' },
    { artist: 'Khalid', title: 'Location' },
    { artist: 'Khalid', title: 'Young Dumb And Broke' }
{ artist: 'Kings of Leon', title: 'Sex On Fire' },
    { artist: 'KT Tunstall', title: 'Black Horse And The Cherry Tree' },
    { artist: 'Lady A (Lady Antebellum)', title: 'Need You Now' },
    { artist: 'Lee DeWyze', title: 'Falling Slowly' },
    { artist: 'Lenny Kravitz', title: 'Fly Away Acoustic' },
    { artist: 'Lewis Capaldi', title: 'Before You Go' },
    { artist: 'Lewis Capaldi', title: 'Bruises' },
    { artist: 'Linkin Park', title: 'Numb' },
    { artist: 'Linkin Park', title: 'What Ive Done  ' },
    { artist: 'Live', title: 'Lightning Crashes' },
    { artist: 'Lord Huron', title: 'The Night We Met' },
    { artist: 'Lukas Graham', title: '7 Years' },
    { artist: 'Lukas Graham', title: 'Love Someone' },
    { artist: 'Luke Combs', title: 'Beautiful Crazy' },
    { artist: 'Måneskin', title: 'Beggin' },
    { artist: 'Marcy Playground', title: 'Sex And Candy' },
    { artist: 'Maren Morris', title: 'The Bones' },
    { artist: 'Maroon 5', title: 'Daylight' },
    { artist: 'Maroon 5', title: 'Girls Like You' },
    { artist: 'Maroon 5', title: 'Memories' },
    { artist: 'Maroon 5', title: 'Misery  ' },
    { artist: 'Maroon 5', title: 'One More Night  ' },
    { artist: 'Maroon 5', title: 'Sunday Morning' },
    { artist: 'Maroon 5', title: 'This Love  ' },
    { artist: 'Maroon 5', title: 'Wont Go Home Without You' },
    { artist: 'Matchbox Twenty', title: '3AM' },
    { artist: 'Matchbox Twenty', title: 'Unwell  ' },
    { artist: 'Matt Maeson', title: 'Hallucinogenics' },
    { artist: 'Matt Maltese', title: 'As The World Caves In' },
    { artist: 'Matt Nathanson', title: 'Come On Get Higher' },
    { artist: 'Matt Simons', title: 'Catch And Release' },
    { artist: 'MAX (Max Schneider)', title: 'Lights Down Low  ' },
    { artist: 'Mayday Parade', title: 'Jamie All Over Acoustic  ' },
    { artist: 'Meghan Trainor', title: 'Like Im Gonna Lose You  ' },
    { artist: 'Michael Bublé', title: 'Everything' },
    { artist: 'Michael Bublé', title: 'Feeling Good' },
    { artist: 'Michael Bublé', title: 'Havent Met You Yet  ' },
    { artist: 'Milky Chance', title: 'Stolen Dance' },
    { artist: 'Misc Cartoons', title: 'Arcane - Enemy' },
    { artist: 'Modest Mouse', title: 'Float On' },
    { artist: 'Morgan Wallen', title: 'Cover Me Up' },
    { artist: 'Mumford & Sons', title: 'Awake My Soul' },
    { artist: 'Mumford & Sons', title: 'I Will Wait  ' },
    { artist: 'Mumford & Sons', title: 'Little Lion Man' },
    { artist: 'Mumford & Sons', title: 'The Cave' },
    { artist: 'My Chemical Romance', title: 'Welcome To The Black Parade' },
    { artist: 'Neon Trees', title: 'Everybody Talks' },
    { artist: 'NF', title: 'If You Want Love' },
    { artist: 'Niall Horan', title: 'This Town' },
    { artist: 'Nickelback', title: 'Far Away' },
    { artist: 'Nickelback', title: 'How You Remind Me Acoustic' },
    { artist: 'Nickelback', title: 'If Today Was Your Last Day' },
    { artist: 'Nirvana', title: 'Come As You Are Acoustic' },
    { artist: 'Nirvana', title: 'Heart Shaped Box' },
    { artist: 'Oasis', title: 'Champagne Supernova' },
    { artist: 'Oasis', title: 'Wonderwall' },
    { artist: 'Of Monsters and Men', title: 'Little Talks' },
    { artist: 'Of Monsters and Men', title: 'Mountain Sound' },
    { artist: 'One Direction', title: 'Night Changes' },
    { artist: 'OneRepublic', title: 'Counting Stars' },
    { artist: 'Passenger', title: 'Let Her Go' },
    { artist: 'Peach Tree Rascals', title: 'Mariposa' },
    { artist: 'Pearl Jam', title: 'Better Man' },
    { artist: 'Pearl Jam', title: 'Last Kiss' },
    { artist: 'Phillip Phillips', title: 'Gone Gone Gone' },
    { artist: 'Phillip Phillips', title: 'Home  ' },
    { artist: 'Portugal. The Man', title: 'Feel It Still' },
    { artist: 'Portugal. The Man', title: 'Live In The Moment' },
    { artist: 'Post Malone', title: 'I Fall Apart Acoustic' },
    { artist: 'Radiohead', title: 'Creep' },
    { artist: 'Rascal Flatts', title: 'Life Is A Highway' },
    { artist: 'Rascal Flatts', title: 'These Days   ' },
    { artist: 'Red Hot Chili Peppers', title: 'Californication' },
    { artist: 'Red Hot Chili Peppers', title: 'Snow Hey Oh' },
    { artist: 'Rex Orange County', title: 'Loving Is Easy  ' },
    { artist: 'Rihanna', title: 'Stay' },
    { artist: 'Rixton', title: 'Me And My Broken Heart' },
    { artist: 'Ron Pope', title: 'A Drop In The Ocean' },
    { artist: 'Ruth B.', title: 'Lost Boy' },
    { artist: 'Ryan Adams', title: 'When The Stars Go Blue' },
    { artist: 'Sam Smith', title: 'Im Not The Only One' },
    { artist: 'Sam Smith', title: 'Stay With Me  ' },
    { artist: 'Sam Smith', title: 'Too Good At Goodbyes' },
    { artist: 'Santana', title: 'Into The Night' },
    { artist: 'Secondhand Serenade', title: 'Fall For You' },
    { artist: 'Semisonic', title: 'Closing Time' },
    { artist: 'Shawn Mendes', title: 'Stitches  ' },
    { artist: 'Shawn Mendes', title: 'Treat You Better  ' },
    { artist: 'Shinedown', title: 'If You Only Knew  ' },
    { artist: 'Shinedown', title: 'Second Chance  ' },
    { artist: 'Shinedown', title: 'Simple Man' },
    { artist: 'Sixpence None the Richer', title: 'Kiss Me  ' },
    { artist: 'Sixpence None the Richer', title: 'There She Goes' },
    { artist: 'Smash Mouth', title: 'All Star' },
    { artist: 'Snow Patrol', title: 'Chasing Cars' },
    { artist: 'Soundgarden', title: 'Black Hole Sun' },
    { artist: 'Stevie Ray Vaughan & Double Trouble', title: 'Pride And Joy' }
{ artist: 'Stevie Wonder', title: 'Isnt She Lovely  ' },
    { artist: 'Sting', title: 'Shape Of My Heart' },
    { artist: 'Sub Urban', title: 'Cradles' },
    { artist: 'Sublime', title: 'Santeria' },
    { artist: 'Sublime', title: 'What I Got' },
    { artist: 'Surf Mesa', title: 'Ily I Love You Baby' },
    { artist: 'Tai Verdes', title: 'Drugs' },
    { artist: 'The All-American Rejects', title: 'Dirty Little Secret Acoustic' },
    { artist: 'The All-American Rejects', title: 'Gives You Hell' },
    { artist: 'The Animals', title: 'House Of The Rising Sun' },
    { artist: 'The Beatles', title: 'Come Together' },
    { artist: 'The Black Keys', title: 'Fever' },
    { artist: 'The Black Keys', title: 'Howling For You' },
    { artist: 'The Black Keys', title: 'Little Black Submarines  ' },
    { artist: 'The Black Keys', title: 'Lonely Boy  ' },
    { artist: 'The Black Keys', title: 'Tighten Up  ' },
    { artist: 'The Chainsmokers', title: 'Closer' },
    { artist: 'The Chainsmokers', title: 'Dont Let Me Down' },
    { artist: 'The Chainsmokers', title: 'Something Just Like This  ' },
    { artist: 'The Cranberries', title: 'Zombie' },
    { artist: 'The Downtown Fiction', title: 'I Just Wanna Run  ' },
    { artist: 'The Foundations', title: 'Build Me Up Buttercup' },
    { artist: 'The Fray', title: 'How To Save A Life' },
    { artist: 'The Fray', title: 'Never Say Never' },
    { artist: 'The Fray', title: 'Over My Head Cable Car' },
    { artist: 'The Fray', title: 'You Found Me' },
    { artist: 'The Head and the Heart', title: 'Rivers And Roads' },
    { artist: 'The Killers', title: 'All These Things That Ive Done' },
    { artist: 'The Killers', title: 'Mr Brightside' },
    { artist: 'The Killers', title: 'When You Were Young' },
    { artist: 'The Lumineers', title: 'Angela Acoustic' },
    { artist: 'The Lumineers', title: 'Cleopatra Acoustic' },
    { artist: 'The Lumineers', title: 'Gloria' },
    { artist: 'The Lumineers', title: 'Ho Hey  ' },
    { artist: 'The Lumineers', title: 'Ophelia' },
    { artist: 'The Lumineers', title: 'Stubborn Love  ' },
    { artist: 'The National Parks', title: 'You Are Gold' },
    { artist: 'The Neighbourhood', title: 'Sweater Weather Acoustic' },
    { artist: 'The Script', title: 'Breakeven' },
    { artist: 'The Script', title: 'For The First Time  ' },
    { artist: 'The Script', title: 'Nothing' },
    { artist: 'The Script', title: 'The Man Who Cant Be Moved' },
    { artist: 'The Weeknd', title: 'Blinding Lights' },
    { artist: 'The Who', title: 'The Seeker' },
    { artist: 'The Wrecks', title: 'Favorite Liar' },
    { artist: 'Theory of a Deadman', title: 'Rx Medicate' }
{ artist: 'Third Eye Blind', title: 'Jumper  ' },
    { artist: 'Tommy Tutone', title: '867-5309 Jenny' },
    { artist: 'Tones And I', title: 'Dance Monkey' },
    { artist: 'Tracy Chapman', title: 'Fast Car' },
    { artist: 'Tracy Chapman', title: 'Give Me One Reason' },
    { artist: 'Train', title: '50 Ways To Say Goodbye' },
    { artist: 'Train', title: 'Drive By' },
    { artist: 'Train', title: 'Drops Of Jupiter' },
    { artist: 'Train', title: 'Hey Soul Sister  ' },
    { artist: 'Train', title: 'Meet Virginia' },
    { artist: 'Travie McCoy', title: 'Billionaire Acoustic' },
    { artist: 'Two Feet', title: 'I Feel Like Im Drowning' },
    { artist: 'Tyler Childers', title: 'Lady May' },
    { artist: 'Tyler Childers', title: 'Nose On The Grindstone' },
    { artist: 'Tyler Childers', title: 'White House Road' },
    { artist: 'U2', title: 'Every Breaking Wave' },
    { artist: 'U2', title: 'I Still Havent Found What Im Looking For' },
    { artist: 'Uncle Lucius', title: 'Keep The Wolves Away' },
    { artist: 'Van Morrison', title: 'Brown Eyed Girl' },
    { artist: 'Vance Joy', title: 'Fire And The Flood' },
    { artist: 'Vance Joy', title: 'Georgia  ' },
    { artist: 'Vance Joy', title: 'Mess Is Mine' },
    { artist: 'Vance Joy', title: 'Saturday Sun' },
    { artist: 'WALK THE MOON', title: 'Shut Up And Dance' },
    { artist: 'Weezer', title: 'Island In The Sun' },
    { artist: 'X Ambassadors', title: 'Unsteady' },
    { artist: 'Young the Giant', title: 'Cough Syrup' },
    { artist: 'Young the Giant', title: 'My Body' },
    { artist: 'Zac Brown Band', title: 'Chicken Fried' },
    { artist: 'Zac Brown Band', title: 'Colder Weather' }
].sort((a, b) => {
  // sort artist
  const artist = a.artist > b.artist ? 1 : b.artist > a.artist ? -1 : 0;
  if (artist !== 0) {
    return artist;
  }

  // sort song
  return a.title > b.title ? 1 : b.title > a.title ? -1 : 0;
});
